import streamlit as st
import os
import re
import json
import pandas as pd
import glob
from datetime import datetime

# --- CONFIGURATION ---
LOG_ROOT = "logs/module_manager_test_v5"

st.set_page_config(page_title="LLM Validation Arena v5", layout="wide")

# --- DATA LOADING & PARSING ---
def parse_run_config(filepath):
    """
    Parses the run_config.json file to extract temperature, language, num_references, and policy.
    """
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            config = json.load(f)
        return {
            "temperature": config.get("temperature", None),
            "language": config.get("language", None),
            "num_references": config.get("num_references", None),
            "policy": config.get("policy", "strict")  # Default to strict if not specified
        }
    except Exception as e:
        return None

def parse_performance_file(filepath):
    """
    Parses the performance.txt file generated by LlmEventValidator.
    Extracts Precision, Recall, and Total Tokens.
    """
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Regex to find metrics in your specific log format
        prec_match = re.search(r"Precision:\s+([0-9.]+)", content)
        rec_match = re.search(r"Recall:\s+([0-9.]+)", content)
        tok_match = re.search(r"Total tokens used:\s+(\d+)", content)
        
        return {
            "Precision": float(prec_match.group(1)) if prec_match else 0.0,
            "Recall": float(rec_match.group(1)) if rec_match else 0.0,
            "Tokens": int(tok_match.group(1)) if tok_match else 0
        }
    except Exception as e:
        return None

def load_all_run_data(module_filter):
    """
    Traverses the log directory structure:
    logs/module_manager_test_v5/{module_id}/event{id}_{date}_{time}_run{index}/
      - run_config.json
      - {model_name}/performance.txt
    
    Loads all runs and groups by configuration.
    """
    data = []
    
    # Find all event folders for the selected module
    module_path = os.path.join(LOG_ROOT, module_filter)
    if not os.path.exists(module_path):
        return pd.DataFrame()
    
    event_folders = sorted(glob.glob(os.path.join(module_path, "event*")))
    
    for event_path in event_folders:
        folder_name = os.path.basename(event_path)
        
        # Extract timestamp and run index for "Last Run" logic
        # Format: event102_20260119_094358_run5
        try:
            parts = folder_name.split('_')
            if len(parts) >= 4:  # event, YYYYMMDD, HHMMSS, run{index}
                timestamp_str = '_'.join(parts[1:3])
                run_part = parts[3]  # "run5" format
                run_index = int(run_part.replace('run', '')) if run_part.startswith('run') else 0
                timestamp = datetime.strptime(timestamp_str, "%Y%m%d_%H%M%S")
            else:
                timestamp = datetime.min
                run_index = 0
        except:
            timestamp = datetime.min
            run_index = 0

        # Read run_config.json to get configuration parameters
        config_file = os.path.join(event_path, "run_config.json")
        if not os.path.exists(config_file):
            continue
        
        run_config = parse_run_config(config_file)
        if not run_config:
            continue
        
        # Find all model folders inside the event folder
        model_folders = [f for f in os.listdir(event_path) 
                        if os.path.isdir(os.path.join(event_path, f)) and f != "." and f != ".."]
        
        for model_safe_name in model_folders:
            perf_file = os.path.join(event_path, model_safe_name, "performance.txt")
            if os.path.exists(perf_file):
                metrics = parse_performance_file(perf_file)
                if metrics:
                    metrics['Date'] = timestamp
                    metrics['RunIndex'] = run_index
                    metrics['RunID'] = folder_name
                    metrics['Temperature'] = run_config.get("temperature")
                    metrics['Language'] = run_config.get("language")
                    metrics['NumReferences'] = run_config.get("num_references")
                    metrics['Policy'] = run_config.get("policy", "strict")
                    # Create config string for grouping and display
                    metrics['Config'] = f"temp={run_config.get('temperature'):.2f} | lang={run_config.get('language')} | refs={run_config.get('num_references')} | policy={run_config.get('policy')}"
                    data.append(metrics)
                    
    return pd.DataFrame(data)

# --- UI LAYOUT ---

st.title("🏆 LLM Validation Arena Leaderboard v5")
st.markdown("Benchmarking configuration performance on module validation tasks (Single Model: gpt-oss-20b)")

# 1. Sidebar Selector
st.sidebar.header("Configuration")

# Get available modules (folders in LOG_ROOT)
if os.path.exists(LOG_ROOT):
    available_modules = [f for f in os.listdir(LOG_ROOT) 
                        if os.path.isdir(os.path.join(LOG_ROOT, f)) and not f.startswith('.')]
    available_modules = sorted(available_modules)
else:
    available_modules = []

selected_module = st.sidebar.selectbox("Select Module to Inspect", available_modules)

# 2. Load Data
if not os.path.exists(LOG_ROOT):
    st.error(f"Log directory not found: {LOG_ROOT}")
    st.stop()

if not available_modules:
    st.error(f"No modules found in: {LOG_ROOT}")
    st.stop()

df = load_all_run_data(selected_module)

if df.empty:
    st.warning(f"No performance logs found for module: **{selected_module}**")
    st.stop()

# 3. Process Data
# Get Last Run Data - find the most recent (Date, RunIndex) combination
if not df.empty:
    # Sort by Date descending, then RunIndex descending to get the very last run
    df_sorted = df.sort_values(['Date', 'RunIndex'], ascending=[False, False])
    latest_timestamp = df_sorted.iloc[0]['Date']
    latest_run_index = df_sorted.iloc[0]['RunIndex']
    
    # Get all runs from the latest timestamp with the highest run index
    df_last_run = df[(df['Date'] == latest_timestamp) & (df['RunIndex'] == latest_run_index)].copy()
else:
    df_last_run = pd.DataFrame()

# Get Average Data by Config
df_avg = df.groupby('Config')[['Precision', 'Recall', 'Tokens']].mean().reset_index()

# --- DISPLAY LEADERBOARDS ---

st.markdown(f"### Results for Module: `{selected_module}`")
st.info(f"📊 Analyzing **{len(df['RunID'].unique())}** runs | **{len(df['Config'].unique())}** unique configurations")

# Helper to style dataframes
def style_leaderboard(dataframe, sort_by, asc=False):
    sorted_df = dataframe.sort_values(sort_by, ascending=asc).reset_index(drop=True)
    sorted_df.index += 1 # Start rank at 1
    return sorted_df

def format_config_display(config_str):
    """
    Formats config string for better display.
    Input: "temp=0.00 | lang=fr | refs=4 | policy=strict"
    Output: "🌡️ 0.00 | 🗣️ FR | 📚 4 | 📋 STRICT"
    """
    try:
        parts = config_str.split(' | ')
        formatted = []
        for part in parts:
            if 'temp=' in part:
                temp = part.split('=')[1]
                formatted.append(f"🌡️ {temp}")
            elif 'lang=' in part:
                lang = part.split('=')[1].upper()
                formatted.append(f"🗣️ {lang}")
            elif 'refs=' in part:
                refs = part.split('=')[1]
                formatted.append(f"📚 {refs}")
            elif 'policy=' in part:
                policy = part.split('=')[1].upper()
                formatted.append(f"📋 {policy}")
        return " | ".join(formatted)
    except:
        return config_str

tab1, tab2, tab3 = st.tabs(["🧠 Recall", "🎯 Precision", "💰 Token Efficiency"])

with tab1:
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Last Run")
        df_last_display = df_last_run[['Config', 'Recall', 'Policy']].copy()
        df_last_display['Config'] = df_last_display['Config'].apply(lambda x: format_config_display(x))
        st.dataframe(
            style_leaderboard(df_last_display, 'Recall'),
            width='stretch',
            column_config={
                "Recall": st.column_config.ProgressColumn(
                    "Recall Score", format="%.4f", min_value=0, max_value=1
                )
            }
        )
    with col2:
        st.subheader("Historical Average")
        df_avg_display = df_avg[['Config', 'Recall']].copy()
        df_avg_display['Config'] = df_avg_display['Config'].apply(lambda x: format_config_display(x))
        st.dataframe(
            style_leaderboard(df_avg_display, 'Recall'),
            width='stretch',
            column_config={
                "Recall": st.column_config.ProgressColumn(
                    "Avg Recall", format="%.4f", min_value=0, max_value=1
                )
            }
        )

with tab2:
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Last Run")
        df_last_display = df_last_run[['Config', 'Precision', 'Policy']].copy()
        df_last_display['Config'] = df_last_display['Config'].apply(lambda x: format_config_display(x))
        st.dataframe(
            style_leaderboard(df_last_display, 'Precision'),
            width='stretch',
            column_config={
                "Precision": st.column_config.ProgressColumn(
                    "Precision Score", format="%.4f", min_value=0, max_value=1
                )
            }
        )
    with col2:
        st.subheader("Historical Average")
        df_avg_display = df_avg[['Config', 'Precision']].copy()
        df_avg_display['Config'] = df_avg_display['Config'].apply(lambda x: format_config_display(x))
        st.dataframe(
            style_leaderboard(df_avg_display, 'Precision'),
            width='stretch',
            column_config={
                "Precision": st.column_config.ProgressColumn(
                    "Avg Precision", format="%.4f", min_value=0, max_value=1
                )
            }
        )

with tab3:
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Last Run")
        df_last_display = df_last_run[['Config', 'Tokens', 'Policy']].copy()
        df_last_display['Config'] = df_last_display['Config'].apply(lambda x: format_config_display(x))
        st.dataframe(
            style_leaderboard(df_last_display, 'Tokens', asc=True),
            width='stretch'
        )
    with col2:
        st.subheader("Historical Average")
        df_avg_display = df_avg[['Config', 'Tokens']].copy()
        df_avg_display['Config'] = df_avg_display['Config'].apply(lambda x: format_config_display(x))
        st.dataframe(
            style_leaderboard(df_avg_display, 'Tokens', asc=True),
            width='stretch'
        )

# Add a drill-down section
st.divider()
st.subheader("🔍 Detailed Run History by Configuration")
config_options = sorted(df['Config'].unique())
config_drilldown = st.selectbox("Select Configuration for details", config_options, format_func=format_config_display)
history_chart_data = df[df['Config'] == config_drilldown].sort_values('Date')

if not history_chart_data.empty:
    st.line_chart(history_chart_data, x='Date', y=['Precision', 'Recall'])
    
    # Show summary stats for this config
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Avg Precision", f"{history_chart_data['Precision'].mean():.4f}")
    with col2:
        st.metric("Avg Recall", f"{history_chart_data['Recall'].mean():.4f}")
    with col3:
        st.metric("Avg Tokens", f"{history_chart_data['Tokens'].mean():.0f}")
    with col4:
        st.metric("Run Count", len(history_chart_data['RunID'].unique()))
