import streamlit as st
import os
import re
import pandas as pd
import glob
from datetime import datetime

# --- CONFIGURATION ---
LOG_ROOT = "logs/module_manager_test_v2"

st.set_page_config(page_title="LLM Validation Arena", layout="wide")

# --- DATA LOADING & PARSING ---
def parse_performance_file(filepath):
    """
    Parses the performance.txt file generated by LlmEventValidator.
    Extracts Precision, Recall, and Total Tokens.
    """
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Regex to find metrics in your specific log format
        prec_match = re.search(r"Precision:\s+([0-9.]+)", content)
        rec_match = re.search(r"Recall:\s+([0-9.]+)", content)
        tok_match = re.search(r"Total tokens used:\s+(\d+)", content)
        
        return {
            "Precision": float(prec_match.group(1)) if prec_match else 0.0,
            "Recall": float(rec_match.group(1)) if rec_match else 0.0,
            "Tokens": int(tok_match.group(1)) if tok_match else 0
        }
    except Exception as e:
        return None

def load_all_run_data(module_filter):
    """
    Traverses the log directory structure:
    logs/event{id}_{date}/{module_id}/{model_name}/performance.txt
    """
    data = []
    
    # Find all event folders
    event_folders = sorted(glob.glob(os.path.join(LOG_ROOT, "event*")))
    
    for event_path in event_folders:
        folder_name = os.path.basename(event_path)
        
        # Extract timestamp for "Last Run" logic
        # Format: event102_20260119_094358
        try:
            timestamp_str = folder_name.split('_', 1)[1]
            timestamp = datetime.strptime(timestamp_str, "%Y%m%d_%H%M%S")
        except:
            timestamp = datetime.min

        # Check for the specific module folder
        module_path = os.path.join(event_path, module_filter)
        if not os.path.exists(module_path):
            continue
            
        # Find all model folders inside the module folder
        # Models often have slashes replaced by underscores in your code
        model_folders = [f for f in os.listdir(module_path) if os.path.isdir(os.path.join(module_path, f))]
        
        for model_safe_name in model_folders:
            perf_file = os.path.join(module_path, model_safe_name, "performance.txt")
            if os.path.exists(perf_file):
                metrics = parse_performance_file(perf_file)
                if metrics:
                    metrics['Model'] = model_safe_name
                    metrics['Date'] = timestamp
                    metrics['RunID'] = folder_name
                    data.append(metrics)
                    
    return pd.DataFrame(data)

# --- UI LAYOUT ---

st.title("🏆 LLM Validation Arena Leaderboard")
st.markdown("Benchmarking model performance on module validation tasks.")

# 1. Sidebar Selector
st.sidebar.header("Configuration")
# In a real scenario, you might scan folders to find available modules
available_modules = ["EventDates","Event", "OwnerPOS", "Prices", "PriceGroups", "RightToSellAndFees", "FeeDefinitions"] 
selected_module = st.sidebar.selectbox("Select Module to Inspect", available_modules)

# 2. Load Data
if os.path.exists(LOG_ROOT):
    df = load_all_run_data(selected_module)
else:
    st.error(f"Log directory not found: {LOG_ROOT}")
    st.stop()

if df.empty:
    st.warning(f"No performance logs found for module: **{selected_module}**")
    st.stop()

# 3. Process Data
# Get Last Run Data
latest_run_id = df.sort_values('Date', ascending=False).iloc[0]['RunID']
df_last_run = df[df['RunID'] == latest_run_id].copy()

# Get Average Data
df_avg = df.groupby('Model')[['Precision', 'Recall', 'Tokens']].mean().reset_index()

# --- DISPLAY LEADERBOARDS ---

st.markdown(f"### Results for Module: `{selected_module}`")
st.info(f"📊 Analyzing **{len(df['RunID'].unique())}** historical runs. Latest run: `{latest_run_id}`")

# Helper to style dataframes
def style_leaderboard(dataframe, sort_by, asc=False):
    sorted_df = dataframe.sort_values(sort_by, ascending=asc).reset_index(drop=True)
    sorted_df.index += 1 # Start rank at 1
    return sorted_df

tab1, tab2, tab3 = st.tabs(["🧠 Recall", "🎯 Precision", "💰 Token Efficiency"])

with tab1:
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Last Run")
        st.dataframe(
            style_leaderboard(df_last_run[['Model', 'Recall']], 'Recall'),
            use_container_width=True,
            column_config={
                "Recall": st.column_config.ProgressColumn(
                    "Recall Score", format="%.4f", min_value=0, max_value=1
                )
            }
        )
    with col2:
        st.subheader("Historical Average")
        st.dataframe(
            style_leaderboard(df_avg[['Model', 'Recall']], 'Recall'),
            use_container_width=True,
            column_config={
                "Recall": st.column_config.ProgressColumn(
                    "Avg Recall", format="%.4f", min_value=0, max_value=1
                )
            }
        )

with tab2:
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Last Run")
        st.dataframe(
            style_leaderboard(df_last_run[['Model', 'Precision']], 'Precision'),
            use_container_width=True,
            column_config={
                "Precision": st.column_config.ProgressColumn(
                    "Precision Score", format="%.4f", min_value=0, max_value=1
                )
            }
        )
    with col2:
        st.subheader("Historical Average")
        st.dataframe(
            style_leaderboard(df_avg[['Model', 'Precision']], 'Precision'),
            use_container_width=True,
            column_config={
                "Precision": st.column_config.ProgressColumn(
                    "Avg Precision", format="%.4f", min_value=0, max_value=1
                )
            }
        )

with tab3:
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Last Run")
        st.dataframe(
            style_leaderboard(df_last_run[['Model', 'Tokens']], 'Tokens', asc=True), # Lower tokens is better
            use_container_width=True
        )
    with col2:
        st.subheader("Historical Average")
        st.dataframe(
            style_leaderboard(df_avg[['Model', 'Tokens']], 'Tokens', asc=True),
            use_container_width=True
        )

# Add a drill-down section
st.divider()
st.subheader("🔍 Detailed Run History")
model_drilldown = st.selectbox("Select Model for details", df['Model'].unique())
history_chart_data = df[df['Model'] == model_drilldown].sort_values('Date')

st.line_chart(history_chart_data, x='Date', y=['Precision', 'Recall'])